spring:
  application:
    # 应用名称
    name: generator-start
  profiles:
    include:
      - knife4j
      - swagger
      - log4j2
      - sleuth
      - datasource
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为 master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost/particle_test?${particle.datasource.mysql.url-query}
          username: root
          password: rootroot
          driver-class-name: ${particle.datasource.mysql.driver} # 3.2.0开始支持SPI可省略此配置
server:
  servlet:
    encoding:
      force: true
