version: '3'
services:
  kibana:
    image: 'kibana:7.14.2'
    container_name: 'particle-kibana'
    networks:
      - particle-kibana-net
    ports:
      # 将容器的5601端口映射到宿主机5601端口
      - '5601:5601'
    volumes:
      # 挂载数据目录到主机上
      # kibana 配置
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  particle-kibana-net:
    driver: bridge