particle:
  mybatis-plus:
      tenant:
        enable: true
mybatis-plus:
  # classpath*:/mapper/**/*.xml 为默认值
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      # 在查询时使用不为空字符串
      where-strategy: NOT_EMPTY
      insert-strategy: NOT_EMPTY
      update-strategy: NOT_EMPTY
