-- import classpath:db/data.func.dict.sql

-- 系统管理一级分组菜单
INSERT INTO `component_func` (`id`, `code`, `name`, `func_group_id`, `icon`, `is_disabled`, `disabled_reason`, `url`, `permissions`, `type_dict_id`, `active_name`, `is_show`, `remark`, `seq`, `level`, `parent_id`, `parent_id1`, `parent_id2`, `parent_id3`, `parent_id4`, `parent_id5`, `parent_id6`, `parent_id7`, `parent_id8`, `parent_id9`, `parent_id10`, `version`, `tenant_id`, `create_at`, `create_by`, `update_at`, `update_by`) VALUES (1, 'system_manage', '系统管理', 1, 'Setting', 0, NULL, NULL, NULL, 21, NULL, 1, NULL, 10, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, '2020-11-27 16:41:31', NULL, NULL, NULL);

-- 功能菜单管理
INSERT INTO `component_func` (`id`, `code`, `name`, `func_group_id`, `icon`, `is_disabled`, `disabled_reason`, `url`, `permissions`, `type_dict_id`, `active_name`, `is_show`, `remark`, `seq`, `level`, `parent_id`, `parent_id1`, `parent_id2`, `parent_id3`, `parent_id4`, `parent_id5`, `parent_id6`, `parent_id7`, `parent_id8`, `parent_id9`, `parent_id10`, `version`, `tenant_id`, `create_at`, `create_by`, `update_at`, `update_by`) VALUES (3, 'func_manage', '功能菜单管理', 1, 'Menu', 0, NULL, '/admin/funcManagePage', NULL, 22, NULL, 1, NULL, 20, 2, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, '2020-11-27 16:41:31', NULL, NULL, NULL);
INSERT INTO `component_func` (`id`, `code`, `name`, `func_group_id`, `icon`, `is_disabled`, `disabled_reason`, `url`, `permissions`, `type_dict_id`, `active_name`, `is_show`, `remark`, `seq`, `level`, `parent_id`, `parent_id1`, `parent_id2`, `parent_id3`, `parent_id4`, `parent_id5`, `parent_id6`, `parent_id7`, `parent_id8`, `parent_id9`, `parent_id10`, `version`, `tenant_id`, `create_at`, `create_by`, `update_at`, `update_by`) VALUES (1205368687877005313, 'func_group_manage', '功能组管理', 1, 'Grid', 0, NULL, '/admin/funcGroupManagePage', NULL, 22, NULL, 1, NULL, 10, 2, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1, 1, '2020-11-27 16:41:31', NULL, NULL, NULL);

-- 后台管理分组
INSERT INTO `component_func_group` (`id`, `code`, `name`, `remark`, `version`, `tenant_id`, `create_at`, `create_by`, `update_at`, `update_by`) VALUES (1, 'backend', 'pc或平板后台管理', 'pc或平板后台管理分组', 1, 1, '2020-12-15 13:29:51', NULL, NULL, NULL);
