DROP TABLE IF EXISTS component_func;
CREATE TABLE `component_func` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `code` varchar(255) NOT NULL COMMENT '编码，模糊查询',
  `name` varchar(100) NOT NULL COMMENT '名称，模糊查询',
  `func_group_id` bigint DEFAULT NULL COMMENT '功能分组id',
  `icon` varchar(100) DEFAULT NULL COMMENT '图标',
  `is_disabled` tinyint(1) NOT NULL COMMENT '是否禁用',
  `disabled_reason` varchar(255) DEFAULT NULL COMMENT '禁用原因',
  `url` varchar(300) DEFAULT NULL COMMENT '地址',
  `permissions` varchar(2000) DEFAULT NULL COMMENT 'shiro权限串，多个以逗号分隔',
  `type_dict_id` bigint NOT NULL COMMENT '类型,字典id',
  `active_name` varchar(100) DEFAULT NULL COMMENT '激活菜单标识',
  `is_show` tinyint(1) NOT NULL COMMENT '是否显示',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `seq` int NOT NULL COMMENT '排序,默认按该字段升序排序',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime DEFAULT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`) USING BTREE,
  KEY `type_dict_id` (`type_dict_id`) USING BTREE,
  KEY `is_disabled` (`is_disabled`) USING BTREE,
  KEY `name` (`name`) USING BTREE,
  KEY `seq` (`seq`) USING BTREE,
  KEY `parent_id1` (`parent_id1`) USING BTREE,
  KEY `parent_id2` (`parent_id2`) USING BTREE,
  KEY `parent_id3` (`parent_id3`) USING BTREE,
  KEY `parent_id4` (`parent_id4`) USING BTREE,
  KEY `parent_id5` (`parent_id5`) USING BTREE,
  KEY `parent_id6` (`parent_id6`) USING BTREE,
  KEY `parent_id7` (`parent_id7`) USING BTREE,
  KEY `parent_id8` (`parent_id8`) USING BTREE,
  KEY `parent_id9` (`parent_id9`) USING BTREE,
  KEY `parent_id10` (`parent_id10`) USING BTREE,
  KEY `level` (`level`) USING BTREE,
  KEY `parent_id` (`parent_id`) USING BTREE,
  KEY `application_id` (`func_group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='菜单功能表';
