# ========================= Logging Setting =========================
logging:
  group:
    # 分组
    particle: com.particle
  level:
    # 分组后，可以对组进行日志级别控制，结合 ${logging.group.particle} 使用
    # 将本项目的 com.particle 以trace日志级别打印
    particle: info
  # 日志文件路径,其实带后缀 spring 不指定config也可以，会默认加载
  config: classpath:log4j2-spring.xml
  # 默认只输出日志到控制台，如果要在日志文件中输出，需要如下设置
  file:
    # 如果只设置path，不设置name，默认name为spring.log
    path: logs/${spring.application.name:app}
    # 请设置 spring.application.name
    name: ${logging.file.path}/${spring.application.name:app}.log
# log4j2 线程上下文
log4j2:
  threadContextMap: com.alibaba.ttl.log4j2.TtlThreadContextMap
# 自定义日志配置，对应系统变量 ${sys:ROLLING_FILE_PREFIX}
particle:
  logging:
    file:
      rolling-prefix: ${spring.application.name:app}
