-- 建表语句sql
DROP TABLE IF EXISTS component_tenant;
CREATE TABLE `component_tenant` (
  `id` bigint NOT NULL COMMENT '租户ID',
  `code` varchar(100) NOT NULL COMMENT '租户编码,模糊查询',
  `name` varchar(100) NOT NULL COMMENT '租户名称,模糊查询',
  `is_disabled` tinyint(1) NOT NULL COMMENT '是否禁用',
  `disabled_reason` varchar(255) DEFAULT NULL COMMENT '禁用原因',
  `contact_user_name` varchar(200) DEFAULT NULL COMMENT '联系人姓名',
  `contact_user_email` varchar(300) DEFAULT NULL COMMENT '联系人邮箱',
  `contact_user_phone` varchar(255) DEFAULT NULL COMMENT '联系人电话',
  `tenant_domain` varchar(300) DEFAULT NULL COMMENT '租户域名，可根据域名识别租户如：example.com',
  `tenant_theme` varchar(255) DEFAULT NULL COMMENT '租户主题，一个代表客户端主题样式的字符串',
  `tenant_default_route` varchar(255) DEFAULT NULL COMMENT '租户默认的页面路由',
  `tenant_logo_url` varchar(350) DEFAULT NULL COMMENT '租户logo地址',
  `is_formal` tinyint(1) NOT NULL COMMENT '是否正式，1=正式，0=试用',
  `user_limit_count` int NULL DEFAULT NULL COMMENT '用户数量限制',
  `effective_at` datetime NULL DEFAULT NULL COMMENT '生效日期，从什么时候开始生效',
  `expire_at` datetime NULL DEFAULT NULL COMMENT '过期时间，从什么时候失效',
  `master_user_id` bigint NOT NULL COMMENT '主用户，一般该用户为租户的超级管理员',
  `config_json` varchar(2000) DEFAULT NULL COMMENT '额外配置json',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`) USING BTREE,
  UNIQUE KEY `tenant_domain` (`tenant_domain`) USING BTREE,
  KEY `name` (`name`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='租户表';
