spring:
  application:
    # 应用名称
    name: data-query-start
  profiles:
    include:
      - knife4j
      - swagger
      - log4j2
      - sleuth
      - datasource
      - mybatis-plus
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为 master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost/particle_test?${particle.datasource.mysql.url-query}
          username: root
          password: rootroot
          driver-class-name: ${particle.datasource.mysql.driver} # 3.2.0开始支持SPI可省略此配置
  # 注意，这里的配置是spring的但实现已经自定义，参考 global-datasource-boot-starter 组件 sqlinit 包实现
  sql:
    init:
      schema-locations:
        - classpath:db/schema.data-query.sql
      data-locations:
        - classpath:db/data.data-query.sql
      mode: ALWAYS # ALWAYS NEVER
server:
  servlet:
    encoding:
      # 在接收请求和返回数据，强制 utf-8 编码
      # encoding 配置默认为 utf-8 编码 参见：org.springframework.boot.web.servlet.server.Encoding.DEFAULT_CHARSET
      force: true
