-- 建表语句sql
DROP TABLE IF EXISTS component_message_template;
CREATE TABLE `component_message_template` (
  `id` bigint NOT NULL COMMENT '表主键',
  `code` varchar(255) DEFAULT NULL COMMENT '编码，不能重复',
  `name` varchar(255) NOT NULL COMMENT '模板名称',
  `title_tpl` varchar(255) DEFAULT NULL COMMENT '消息标题模板',
  `title_tpl_memo` varchar(2000) DEFAULT NULL COMMENT '消息标题模板说明',
  `content_tpl` varchar(2000) DEFAULT NULL COMMENT '消息内容模板',
  `content_tpl_memo` varchar(2000) DEFAULT NULL COMMENT '消息内容模板说明',
  `content_detail_json` text DEFAULT NULL COMMENT '详细配置，可根据不同的通知内容细化配置，如短信内容',
  `is_content_html` tinyint(1) NOT NULL COMMENT '内容是否为html，1=是，0=否',
  `type_dict_id` bigint DEFAULT NULL COMMENT '消息模板分类，字典id',
  `is_group` tinyint(1) NOT NULL COMMENT '是否为分组，1=分组，0=模板',
  `group_flag` varchar(255) DEFAULT NULL COMMENT '分组标识',
  `group_flag_memo` varchar(255) DEFAULT NULL COMMENT '分组标识备忘',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签，多个以逗号分隔，用来区分字典项',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `seq` int NOT NULL COMMENT '排序,默认按该字段升序排序',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`,`tenant_id`) USING BTREE,
  KEY `type_dict_id` (`type_dict_id`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='消息内容模板表';
