-- 建表语句sql
DROP TABLE IF EXISTS component_tenant_create_apply;
CREATE TABLE `component_tenant_create_apply` (
  `id` bigint NOT NULL COMMENT '租户ID',
  `name` varchar(100) NOT NULL COMMENT '租户名称,模糊查询',
  `user_name` varchar(200) DEFAULT NULL COMMENT '姓名，没有指定 applyUserId 时，用户创建用户昵称和姓名',
  `account` varchar(255) NULL DEFAULT NULL COMMENT '账号，没有指定 applyUserId 时，用户创建用户登录账号',
  `email` varchar(300) DEFAULT NULL COMMENT '邮箱，没有指定 applyUserId 时，用户创建用户登录账号',
  `mobile` varchar(255) DEFAULT NULL COMMENT '手机号，没有指定 applyUserId 时，用户创建用户登录账号',
  `password` varchar(255) NULL DEFAULT NULL COMMENT '密码，没有指定 applyUserId 时，用户创建用户登录密码',
  `is_send_email_notice` tinyint(1) NOT NULL COMMENT '是否发送邮件通知，1=发送，0=不发送，仅存在邮件箱时发送',
  `is_send_mobile_notice` tinyint(1) NOT NULL COMMENT '是否发送短信通知，1=发送，0=不发送，仅存在手机号时发送',
  `tenant_type_dict_id` bigint NOT NULL COMMENT '租户类型字典id',
  `apply_user_id` bigint DEFAULT NULL COMMENT '申请用户，如果主空意味着联系邮箱和联系电话必须填写一个，将用户创建关联用户',
  `audit_status_dict_id` bigint NOT NULL COMMENT '审核状态，字典id',
  `audit_status_comment` varchar(255) DEFAULT NULL COMMENT '审核意见',
  `audit_user_id` bigint DEFAULT NULL COMMENT '审核用户id',
  `applied_tenant_id` bigint DEFAULT NULL COMMENT '审核通过后创建的租户id',
  `is_formal` tinyint(1) NOT NULL COMMENT '是否正式，1=正式，0=试用',
  `user_limit_count` int NULL DEFAULT NULL COMMENT '用户数量限制',
  `effective_at` datetime NULL DEFAULT NULL COMMENT '生效日期，从什么时候开始生效',
  `effective_days` int NULL DEFAULT NULL COMMENT '申请天数,0或空为不限制',
  `expire_at` datetime NULL DEFAULT NULL COMMENT '过期时间，从什么时候失效',
  `ext_json` mediumtext DEFAULT NULL COMMENT '额外申请项json，如：应用和功能',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `name` (`name`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='租户创建申请表';
