-- 建表语句sql
DROP TABLE IF EXISTS component_tracking_page_record;
CREATE TABLE `component_tracking_page_record` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `user_id` bigint DEFAULT NULL COMMENT '用户id，已注册用户必填',
  `user_nickname` varchar(255) DEFAULT NULL COMMENT '操作用户昵称',
  `user_avatar` varchar(500) DEFAULT NULL COMMENT '操作用户头像',
  `is_user_trigger` tinyint(1) NOT NULL COMMENT '是否用户触发，可以表名是否用户参与',
  `session` varchar(500) NOT NULL COMMENT '会话标识，登录成功后的会话',
  `session_md5` varchar(255) NOT NULL COMMENT '会话标识的md5摘要值，考虑到会话标识可能会很长',
  `imei` varchar(50) DEFAULT NULL COMMENT '设备串号，安卓:（imei），IOS:（idfa），未注册用户必填',
  `device_id` varchar(500) NOT NULL COMMENT '设备id，可以用来唯一标识一个设备',
  `device_name` varchar(255) NOT NULL COMMENT '设备名称，如：xxx的Iphone',
  `tracking_page_code` varchar(50) NOT NULL COMMENT '埋点页面编码',
  `pre_tracking_page_code` varchar(50) NOT NULL COMMENT '埋点前驱页面编码',
  `operating_system` varchar(255) NOT NULL COMMENT '操作系统及版本',
  `app_version` varchar(255) NOT NULL COMMENT '客户端版本',
  `action_type` varchar(20) NOT NULL COMMENT '行为类型，例如曝光、停留、点击、收藏、下载、购买、加购、评价等',
  `action_at` datetime NOT NULL COMMENT '行为产生时间',
  `action_result` varchar(20) DEFAULT NULL COMMENT '行为值，例如点击次数，停留时长，购买件数、购买金额等',
  `action_on_x` int DEFAULT NULL COMMENT '行为位置 x',
  `action_on_y` int DEFAULT NULL COMMENT '行为位置 y',
  `net_type` varchar(20) NOT NULL COMMENT '网络类型，2G/3G/4G/WIFI',
  `ip` varchar(500) NULL DEFAULT NULL COMMENT '请求ip',
  `longitude` varchar(50) DEFAULT NULL COMMENT '位置经度',
  `latitude` varchar(50) DEFAULT NULL COMMENT '位置纬度',
  `screen_height` int NOT NULL COMMENT '屏幕高度，一般单位为像素',
  `screen_width` int NOT NULL COMMENT '屏幕宽度，一般单位为像素',
  `entry_at` datetime DEFAULT NULL COMMENT '进入页面时间',
  `leave_at` datetime DEFAULT NULL COMMENT '离开页面时间',
  `duration` bigint DEFAULT NULL COMMENT '页面停留时长，单位ms',
  `ext_info_json` varchar(2000) DEFAULT NULL COMMENT '额外数据，用于描述该事件的额外数据，比如加载成功后的结果数据',
  `trace_id` varchar(50) NOT NULL COMMENT '追踪id',
  `front_trace_id` varchar(100) DEFAULT NULL COMMENT '前端追踪id，一般从二级页面开始设置后续操作都使用该id',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `tracking_page_code` (`tracking_page_code`) USING BTREE,
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `action_type_dict_id` (`action_type`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='页面埋点记录表';
