-- 建表语句sql
DROP TABLE IF EXISTS component_tracking_page;
CREATE TABLE `component_tracking_page` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `code` varchar(100) NOT NULL COMMENT '页面编码,模糊查询',
  `name` varchar(100) NOT NULL COMMENT '页面名称,模糊查询',
  `image_url` varchar(500) NOT NULL COMMENT '页面图片地址',
  `absolute_url` varchar(500) NOT NULL COMMENT '页面访问地址',
  `path_memo` varchar(1000) NOT NULL COMMENT '路径说明，说明如何进入到该页面',
  `page_version` varchar(255) NOT NULL COMMENT '页面版本',
  `group_flag` varchar(255) NOT NULL COMMENT '分组标识，一个字符串可以区分不同的页面，pc、app等',
  `seq` int NOT NULL COMMENT '排序,默认按该字段升序排序',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uni_code` (`code`) USING BTREE,
  KEY `idx_name` (`name`) USING BTREE,
  KEY `seq` (`seq`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='埋点页面表';
