<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>global</artifactId>
        <groupId>com.particle</groupId>
        <version>7.0.1-beta-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>global-autoconfigure-boot-starter</artifactId>

    <properties>


    </properties>

    <dependencies>
        <!-- 为了方便引入，直接引入web编译 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <optional>true</optional>
            <exclusions>
                <!-- 排除默认的logback，使用log4j2 -->
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <!-- 主要为自动注入 springContextHolder -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>global-tool</artifactId>
            <version>${particle.version}</version>
        </dependency>
        <!-- 依赖数据源本模块目前使用pg相关操作,可选，主要是用来切换数据源-->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>global-datasource-boot-starter</artifactId>
            <version>${particle.version}</version>
            <optional>true</optional>
        </dependency>
        <!-- 用于配置拦截器，添加主要是统一远程调用传递租户id -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-openfeign</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- 当前添加主要是使用租户常量，远程调用传递 -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>global-common</artifactId>
            <version>${particle.version}</version>
        </dependency>
        <!-- 版本已在 spring-boot-starter-parent 中定义 -->
        <!-- 主要实现在 feign 调用时传递 traceId 信息 -->
        <dependency>
            <groupId>io.github.openfeign</groupId>
            <artifactId>feign-micrometer</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>
</project>
