spring:
  application:
    # 应用名称
    name: particle-project-lite-start
  profiles:
    include:
      - knife4j
      - swagger
      - log4j2
      - datasource
      - mybatis-plus
      - mybatis-plus-tenant
      - actuator
      - boot-admin-client-local
      - boot-admin-server
      - session
      - resourceserver-local
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为 master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          # 数据库连接地址如：jdbc:mysql://localhost/particle_test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
          url: ${particle.datasource.master.url}?${particle.datasource.mysql.url-query}
          # 数据库连接用户名
          username: root
          # 数据库连接密码
          password: rootroot
          driver-class-name: ${particle.datasource.mysql.driver} # 3.2.0开始支持SPI可省略此配置
        # postgresql 主要用于ai存储向量
#        masterPg:
#          url: jdbc:postgresql://localhost/particle_test?${particle.datasource.postgresql.url-query:}
#          username: postgres
#          password: postgrespostgres
#          driver-class-name: ${particle.datasource.postgresql.driver}

  # 注意，这里的配置是spring的但实现已经自定义，参考 global-datasource-boot-starter 组件 sqlinit 包实现
  sql:
    init:
      schema-locations:
        - classpath:db/schema.particle-project.sql
        - classpath:db/schema.area.sql
        - classpath:db/schema.dict.sql
        - classpath:db/schema.func.sql
        - classpath:db/schema.user.sql
        - classpath:db/schema.role.sql
        - classpath:db/schema.tenant.sql
        - classpath:db/schema.op-log.sql
        - classpath:db/schema.global_spring_session.sql
        - classpath:db/schema.global_concurrency_shedlock.sql
        - classpath:db/schema.global_captcha.sql
        - classpath:db/schema.data-constraint.sql
      data-locations:
        - classpath:db/data.particle-project.sql
        - classpath:db/data.area.sql
        - classpath:db/data.dict.sql
        - classpath:db/data.func.sql
        - classpath:db/data.user.sql
        - classpath:db/data.role.sql
        - classpath:db/data.role.virtual_superadmin.sql
        - classpath:db/data.tenant.sql
        - classpath:db/data.op-log.sql
        - classpath:db/data.data-constraint.sql
      # 默认 NEVER，太危险了，因为本机开发有部分是脚本配置依赖数据，比如数据查询和报告模板等，换了一个环境，全部数据没有了，还好通过binlog恢复了
      mode: NEVER # ALWAYS NEVER
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 50MB
  mvc:
    async:
      # 在agent流式对话中ai响应持续时间可能较慢，这里需要调整一下时间，目前15分钟
      request-timeout: 15m

server:
  port: 8009
  servlet:
    encoding:
      # 在接收请求和返回数据，强制 utf-8 编码
      # encoding 配置默认为 utf-8 编码 参见：org.springframework.boot.web.servlet.server.Encoding.DEFAULT_CHARSET
      force: true
    session:
      timeout: 7d
  error:
    include-exception: true
    include-binding-errors: always
    include-stacktrace: always

particle:
  global:
    session:
      # 使用jdbc存储session，如果单机部署可以使用内存存储，改为 none
       store-type: jdbc
   # 参见 com.particle.global.projectinfo.ProjectInfo
    project-info:
      component:
        # 后端组件全部启用
        enable:
          all: true
    captcha:
     # 参见 com.particle.global.captcha.security.CaptchaSecurityFilter
     filter:
       enabled: true
       uris:
         # 登录添加验证码校验
         - /login
         # 获取动态验证码，需要先校验静态验证码
         - /captcha/getDynamicCaptcha
       # 以下 check 配置仅在 /login 登录时，配置哪些用户不需要验证码
       #check:
         #no-captcha-login-usernames:
         #  - superadmin
     dynamic-captcha:
        # 参见 com.particle.global.captcha.security.DynamicCaptchaSecurityFilter
        filter:
          enabled: true
          uris:
            # 这里随便举例 动态验证码登录独立校验，不需要该拦截器支持，如果配置会有冲突
            - /loginCaptcha
            - /user-identifier-pwd/login/user/findBackPassword
          uriIdentifier:
            '[/loginCaptcha]': username
            '[/user-identifier-pwd/login/user/findBackPassword]': identifier
        # 参见 com.particle.global.captcha.endpoint.DynamicCaptchaNotifyProperties
        notifyIdentifiers:
          # 配置发送动态验证码的模板
          # 如果 key 中有特殊字符 需要加中括号,并使用双引号（单引号也可以），参考：https://blog.csdn.net/weixin_38295272/article/details/117631314
          '[/loginCaptcha]': user_login_dynamic_captcha
          '[/user-identifier-pwd/login/user/findBackPassword]': user_find_back_password_dynamic_captcha
        # 该配置对应 com.particle.global.oss.GlobalOssProperties 配置属性
    oss:
      defaultClient: localClient
      concatEndpoint: false
      local:
        localClient:
          # 访问的地址
          endpoint: http://localhost:8080/oss/download
          basePath: /Users/yw/temp/localosstest
          bucketName: localClientBucket
    # 参见 com.particle.global.notification.GlobalNotificationProperties
    notification:
      # 提供系统级别的全局邮件通知配置
      email:
        # 邮件服务器的SMTP地址，可选，默认为smtp.<发件人邮箱后缀>
        host: smtp.163.com
        # 邮件服务器的SMTP端口，可选，默认25
        port: 25
        # 发件人（必须正确，否则发送失败）
        from: particle_particle@163.com
        # 用户名，默认为发件人邮箱前缀,注意用户名和密码需要匹配，否则认证失败
        user: particle_particle
        # 密码（注意，某些邮箱需要为SMTP服务单独设置授权码，详情查看相关帮助）163 邮箱密码不是用户登录密码，是邮箱的授权码
        pass: xxxx
      #alert:
      #  wxcpWebhooks:
      #    - https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxx

