<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>global</artifactId>
        <groupId>com.particle</groupId>
        <version>7.0.2-beta</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>global-dto</artifactId>

    <properties>


    </properties>

    <dependencies>

        <!-- 仅使用注解 swagger 接口文档工具-->
        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations-jakarta</artifactId>
            <version>${swagger-annotations-jakarta.version}</version>
            <optional>true</optional>
        </dependency>
        <!-- 仅使用注解 版本已在spring父级定义 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
            <exclusions>
                <!-- 排除默认的logback，使用log4j2 -->
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-logging</artifactId>
                </exclusion>
            </exclusions>
            <optional>true</optional>
        </dependency>
        <!-- 仅使用注解，主要是使用 @JsonProperty -->
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <optional>true</optional>
        </dependency>
        <!-- 仅使用注解，主要是为了使用其 com.particle.global.light.share.mybatis.anno.Ignore -->
        <!-- 使用 IErrorCode 接口，在响应对应中使用 -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>global-common</artifactId>
            <version>${particle.version}</version>
        </dependency>
    </dependencies>
</project>
