<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>common</artifactId>
        <groupId>com.particle</groupId>
        <version>7.0.1-beta-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>common-app</artifactId>

    <description>
        DDD 架构中的通用应用层模块，负责编排和协调领域层能力，
        对外提供可复用的应用服务与用例接口，
        用于承接适配层的调用请求，不包含具体技术实现与基础设施细节。
    </description>

    <properties>


    </properties>

    <dependencies>
        <!-- 依赖客户端 不传递依赖 -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>common-client</artifactId>
            <version>${particle.version}</version>
            <optional>true</optional>
        </dependency>
        <!-- 依赖基础设施 不传递依赖 -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>common-infrastructure</artifactId>
            <version>${particle.version}</version>
            <optional>true</optional>
        </dependency>

        <!-- 参数验证 依赖 -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>global-validation-boot-starter</artifactId>
            <version>${particle.version}</version>
        </dependency>
        <!-- 全局异常日志并打印 依赖 -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>global-catchlog-boot-starter</artifactId>
            <version>${particle.version}</version>
        </dependency>
    </dependencies>

</project>
