-- 建表语句sql
DROP TABLE IF EXISTS component_crm_customer;
CREATE TABLE `component_crm_customer` (
  `id` bigint NOT NULL COMMENT 'id主键',
  `code` varchar(255) DEFAULT NULL COMMENT '客户编码',
  `name` varchar(255) NOT NULL COMMENT '客户名称',
  `appellation` varchar(100) DEFAULT NULL COMMENT '客户称呼',
  `type_dict_id` bigint NOT NULL COMMENT '客户类型，字典id，如：个人、企业',
  `gender_dict_id` bigint DEFAULT NULL COMMENT '客户性别，字典id',
  `age` int DEFAULT NULL COMMENT '客户年龄',
  `birth_day` date DEFAULT NULL COMMENT '客户生日',
  `crm_company_id` bigint DEFAULT NULL COMMENT '客户公司id',
  `crm_dept_id` bigint DEFAULT NULL COMMENT '客户公司部门id',
  `is_black` tinyint(1) NOT NULL COMMENT '是否为黑名单',
  `black_reason` varchar(200) DEFAULT NULL COMMENT '黑名单原因',
  `category_dict_id` bigint DEFAULT NULL COMMENT '客户分类，字典id,如：新客户、老客户',
  `belong_user_id` bigint DEFAULT NULL COMMENT '归属用户id',
  `belong_comp_id` bigint DEFAULT NULL COMMENT '归属用户的公司id',
  `belong_dept_id` bigint DEFAULT NULL COMMENT '归属用户的部门id',
  `union_id` bigint DEFAULT NULL COMMENT '唯一id，有可能不同的客户数据其实是同一个客户，这里唯一标识，默认为主键id',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`),
  KEY `type_dict_id` (`type_dict_id`) USING BTREE,
  KEY `crm_company_id` (`crm_company_id`) USING BTREE,
  KEY `crm_dept_id` (`crm_dept_id`) USING BTREE,
  KEY `category_dict_id` (`category_dict_id`) USING BTREE,
  KEY `belong_user_id` (`belong_user_id`) USING BTREE,
  KEY `belong_comp_id` (`belong_comp_id`) USING BTREE,
  KEY `belong_dept_id` (`belong_dept_id`) USING BTREE,
  KEY `union_id` (`union_id`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='客户表';
