-- import classpath:db/generator/schema.component_lowcode_datasource.sql
-- import classpath:db/generator/schema.component_lowcode_model.sql
-- import classpath:db/generator/schema.component_lowcode_model_item.sql
-- import classpath:db/generator/schema.component_lowcode_segment_template.sql