version: '3'
services:
  pandora-next:
    image: pengzhile/pandora-next
    container_name: particle-pandora-next
    network_mode: bridge
    restart: always
    ports:
      - "9191:9191"
    volumes:
      - ./data:/data
      - ./sessions:/root/.cache/PandoraNext
