spring:
  session:
    jdbc:
      # springboot3增加了校验不能设置为空了
      table-name: global_spring_session
particle:
  session:
    jdbc:
      type: mysql
    # 默认使用header不使用cookie
    session-id-resolver: header
