-- 建表语句sql
DROP TABLE IF EXISTS component_openplatform_openapi;
CREATE TABLE `component_openplatform_openapi` (
  `id` bigint NOT NULL COMMENT '表主键',
  `code` varchar(50) DEFAULT NULL COMMENT '编码',
  `name` varchar(255) NOT NULL COMMENT '名称',
  `is_group` tinyint(1) NOT NULL COMMENT '是否为组，1=组，0=接口',
  `permissions` varchar(2000) DEFAULT NULL COMMENT '接口权限码',
  `url` varchar(255) DEFAULT NULL COMMENT '接口地址，以/开头，用于匹配',
  `is_disabled` tinyint(1) NOT NULL COMMENT '是否禁用',
  `disabled_reason` varchar(255) DEFAULT NULL COMMENT '禁用原因',
  `default_openplatform_openapi_fee_id` bigint DEFAULT NULL COMMENT '默认计费id，不配置不计费',
  `openplatform_provider_ids` varchar(2000) DEFAULT NULL COMMENT '可用供应商',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`),
  UNIQUE KEY `url` (`url`),
  KEY `name` (`name`) USING BTREE,
  KEY `parent_id1` (`parent_id1`) USING BTREE,
  KEY `parent_id2` (`parent_id2`) USING BTREE,
  KEY `parent_id3` (`parent_id3`) USING BTREE,
  KEY `parent_id4` (`parent_id4`) USING BTREE,
  KEY `parent_id5` (`parent_id5`) USING BTREE,
  KEY `parent_id6` (`parent_id6`) USING BTREE,
  KEY `parent_id7` (`parent_id7`) USING BTREE,
  KEY `parent_id8` (`parent_id8`) USING BTREE,
  KEY `parent_id9` (`parent_id9`) USING BTREE,
  KEY `parent_id10` (`parent_id10`) USING BTREE,
  KEY `level` (`level`) USING BTREE,
  KEY `parent_id` (`parent_id`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='开放平台开放接口表';
