-- 建表语句sql
DROP TABLE IF EXISTS component_op_log_error;
CREATE TABLE `component_op_log_error` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `trace_id` varchar(50) DEFAULT NULL COMMENT '日志追踪id',
  `user_id` bigint DEFAULT NULL COMMENT '操作用户id',
  `user_name` varchar(255) DEFAULT NULL COMMENT '操作用户姓名',
  `user_nickname` varchar(255) DEFAULT NULL COMMENT '操作用户昵称',
  `user_avatar` varchar(500) DEFAULT NULL COMMENT '操作用户头像',
  `request_url` varchar(2000) DEFAULT NULL COMMENT '请求地址，要求带http',
  `request_method` varchar(255) DEFAULT NULL COMMENT '请求方法',
  `request_headers` text COMMENT '请求头信息',
  `request_params` text COMMENT '请求参数',
  `request_body` text COMMENT '请求内容',
  `request_ip` varchar(255) DEFAULT NULL COMMENT '请求ip',
  `response_status` int DEFAULT NULL COMMENT '响应的状态码',
  `response_headers` text COMMENT '响应头信息',
  `response_body` text COMMENT '响应内容',
  `local_host_ip` varchar(500) DEFAULT NULL COMMENT '本地主机ip，用来表明是在哪个机器上运行的',
  `local_host_name` varchar(500) DEFAULT NULL COMMENT '本地主机名称，用来表明是在哪个机器上运行的',
  `error_at` datetime NOT NULL COMMENT '异常发生时间',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `trace_id` (`trace_id`),
  KEY `user_id` (`user_id`),
  KEY `error_at` (`error_at`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='操作异常日志表';
