# ========================= swagger config =========================
springdoc:
  # 默认是false，需要设置为true
  # 主要是解决 Knife4j v4.0版本针对参数解析ParameterObject的问题说明 参见：https://doc.xiaominfo.com/docs/faq/v4/knife4j-parameterobject-flat-param
  default-flat-param-object: true
  api-docs:
    enabled: ${particle.swagger.enabled:true}