# ========================= Knife4j Setting =========================
# 参考 https://doc.xiaominfo.com/docs/quick-start
knife4j:
  # 是否开启Knife4j增强模式，增强功能需要通过配置yml配置文件开启增强,自2.0.7开始，只有开启该功能，后面配置才生效
  enable: ${particle.swagger.enabled:true}
  # 前端Ui的个性化配置属性
  setting:
    # 重命名SwaggerModel名称
    swaggerModelName: Swagger Models 实体类列表
    # 是否在每个Debug调试栏后显示刷新变量按钮,默认不显示
    enableReloadCacheParameter: true
    # 是否开启请求参数缓存
    enableRequestCache: false
    # 是否显示Footer
    enableFooter: false
    # 自定义Footer内容
    enableFooterCustom: true
    footerCustomContent: "Powered by <a href='feihihua666@sina.com'>飞华</a> @2022~"
