version: '3'
services:
  elasticsearch:
    image: 'elasticsearch:7.14.2'
    container_name: 'particle-elasticsearch'
    networks:
      - particle-elasticsearch-net
    ports:
      # 将容器的9200端口映射到宿主机9200端口
      - '9200:9200'
      # 将容器的9300端口映射到宿主机9300端口，目的是集群互相通信
      - '9300:9300'
    volumes:
      # 挂载数据目录到主机上
      # elasticsearch 配置
      - particle-elasticsearch-config:/usr/share/elasticsearch/config
      - particle-elasticsearch-data:/usr/share/elasticsearch/data
      - particle-elasticsearch-plugins:/usr/share/elasticsearch/plugins
    environment:
      - "discovery.type=single-node"
networks:
  particle-elasticsearch-net:
    driver: bridge

volumes:
  particle-elasticsearch-config:
    driver: local
  particle-elasticsearch-data:
    driver: local
  particle-elasticsearch-plugins:
    driver: local