version: '3'
services:
  elasticsearch:
    image: 'elasticsearch:7.14.2'
    container_name: 'particle-elasticsearch'
    networks:
      - particle-elasticsearch-net
    ports:
      # 将容器的9200端口映射到宿主机9200端口
      - '9200:9200'
      # 将容器的9300端口映射到宿主机9300端口，目的是集群互相通信
      - '9300:9300'
    volumes:
      # 挂载数据目录到主机上
      # elasticsearch 配置
      - particle-elasticsearch-config:/usr/share/elasticsearch/config
      - particle-elasticsearch-data:/usr/share/elasticsearch/data
      - particle-elasticsearch-plugins:/usr/share/elasticsearch/plugins
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - "discovery.type=single-node"
  kibana:
    image: 'kibana:7.14.2'
    container_name: 'particle-kibana'
    #    network_mode: "host"
    networks:
      # 注意这里使用和 elasticsearch 一样的网络
      - particle-elasticsearch-net
    ports:
      # 将容器的5601端口映射到宿主机5601端口
      - '5601:5601'
    volumes:
      # 挂载数据目录到主机上
      # kibana 配置
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
networks:
  particle-elasticsearch-net:
    driver: bridge

volumes:
  particle-elasticsearch-config:
    driver: local
  particle-elasticsearch-data:
    driver: local
  particle-elasticsearch-plugins:
    driver: local