DROP TABLE IF EXISTS component_dict;
CREATE TABLE `component_dict` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `code` varchar(100) DEFAULT NULL COMMENT '字典编码,模糊查询，字典组时必填',
  `name` varchar(100) NOT NULL COMMENT '字典名称,模糊查询',
  `value` varchar(255) DEFAULT NULL COMMENT '字典值,模糊查询',
  `value_unit` varchar(255) DEFAULT NULL COMMENT '字典值,单位',
  `is_system` tinyint(1) NOT NULL COMMENT '是否为系统字典，一般系统字典代码中会做判断，不能修改或删除',
  `is_public` tinyint(1) NOT NULL COMMENT '是否为公共字典，如果为公共字典不限制使用，否则按相应数据权限查询',
  `is_group` tinyint(1) NOT NULL COMMENT '是否为字典组，不是字典组就是字典项目，没有其它的',
  `is_disabled` tinyint(1) NOT NULL COMMENT '是否禁用',
  `disabled_reason` varchar(255) DEFAULT NULL COMMENT '禁用原因',
  `private_flag` varchar(255) DEFAULT NULL COMMENT '私有标识,模糊查询',
  `private_flag_memo` varchar(255) DEFAULT NULL COMMENT '私有标识备忘',
  `group_flag` varchar(255) DEFAULT NULL COMMENT '分组标识',
  `group_flag_memo` varchar(255) DEFAULT NULL COMMENT '分组标识备忘',
  `tags` varchar(255) DEFAULT NULL COMMENT '标签，多个以逗号分隔，用来区分字典项',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `seq` int NOT NULL COMMENT '排序,默认按该字段升序排序',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `code` (`code`) USING BTREE,
  KEY `name` (`name`) USING BTREE,
  KEY `is_group` (`is_group`) USING BTREE,
  KEY `seq` (`seq`) USING BTREE,
  KEY `parent_id1` (`parent_id1`) USING BTREE,
  KEY `parent_id2` (`parent_id2`) USING BTREE,
  KEY `parent_id3` (`parent_id3`) USING BTREE,
  KEY `parent_id4` (`parent_id4`) USING BTREE,
  KEY `parent_id5` (`parent_id5`) USING BTREE,
  KEY `parent_id6` (`parent_id6`) USING BTREE,
  KEY `parent_id7` (`parent_id7`) USING BTREE,
  KEY `parent_id8` (`parent_id8`) USING BTREE,
  KEY `parent_id9` (`parent_id9`) USING BTREE,
  KEY `parent_id10` (`parent_id10`) USING BTREE,
  KEY `level` (`level`) USING BTREE,
  KEY `parent_id` (`parent_id`) USING BTREE,
  KEY `private_flag` (`private_flag`) USING BTREE,
  KEY `is_group__value` (`is_group`,`value`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='字典表';
