-- 建表语句sql
DROP TABLE IF EXISTS component_cms_site;
CREATE TABLE `component_cms_site` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `code` varchar(100) DEFAULT NULL COMMENT '站点编码',
  `name` varchar(100) NOT NULL COMMENT '站点名称',
  `title` varchar(100) DEFAULT NULL COMMENT '网页标题，用于页面标题',
  `domain` varchar(200) NOT NULL COMMENT '站点域名，仅用来匹配站点',
  `dynamic_domain` varchar(200) NOT NULL COMMENT '站点动态外部域名，用来生成链接',
  `dynamic_deploy_path` varchar(200) DEFAULT NULL COMMENT '动态访问部署路径，主要用于页面组织访问链接路径，该路径和spring context-path无关，一般用于nginx反向代理时可能会配置',
  `site_context_path` varchar(200) DEFAULT NULL COMMENT '站点访问上下文路径，主要应用于动态页访问，可以实现在一个域名下区分不同的站点，该路径和spring context-path无关',
  `template_path` varchar(200) NOT NULL COMMENT '站点模板路径，站点模板存放路径，pc默认default,移动端默认mobile,站点首页模板默认index.ftlh',
  `template_index` varchar(200) NOT NULL COMMENT '站点首页模板,默认index.ftlh',
  `template404_path` varchar(200) DEFAULT NULL COMMENT '404模板路径',
  `template404_index` varchar(200) DEFAULT NULL COMMENT '404内容模板,默认404.ftlh',
  `template403_path` varchar(200) DEFAULT NULL COMMENT '403模板路径',
  `template403_index` varchar(200) DEFAULT NULL COMMENT '403内容模板,默认403.ftlh',
  `template_channel_path` varchar(200) DEFAULT NULL COMMENT 'channel模板路径',
  `template_channel_index` varchar(200) DEFAULT NULL COMMENT 'channel内容模板',
  `template_content_path` varchar(200) DEFAULT NULL COMMENT 'content模板路径',
  `template_content_index` varchar(200) DEFAULT NULL COMMENT 'content内容模板',
  `static_save_path` varchar(200) DEFAULT NULL COMMENT '站点静态化页存放路径，文件系统绝对路径',
  `static_domain` varchar(200) DEFAULT NULL COMMENT '静态化站点域名,主要用于在访问页面时，静态化优先时，优先访问静态化页面',
  `static_deploy_path` varchar(200) DEFAULT NULL COMMENT '静态化访问部署路径，主要用于页面组织访问链接路径，该路径和spring context-path无关，一般用于nginx反向代理时可能会配置',
  `is_prime_site` tinyint(1) NOT NULL COMMENT '是否主站点，同一个域名即domain字段下，只能有一个主站',
  `profile` varchar(200) DEFAULT NULL COMMENT '简介',
  `is_public` tinyint(1) NOT NULL COMMENT '是否发布',
  `public_at` datetime DEFAULT NULL COMMENT '发布时间',
  `is_enable_backend_record` tinyint(1) NOT NULL COMMENT '是否启用后台记录',
  `remark` varchar(200) DEFAULT NULL COMMENT '备注',
  `pv` int NOT NULL COMMENT '页面访问量,页面展示次数',
  `init_pv` int NOT NULL COMMENT '初始页面访问量,页面展示次数',
  `iv` int NOT NULL COMMENT '页面访问ip数,一天之内相同IP地址只被计算一次',
  `uv` int NOT NULL COMMENT '页面访问用户数,页面访问电脑客户端数,一天之内相同cookie的访问只被计算1次',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `name` (`name`) USING BTREE,
  UNIQUE KEY `code` (`code`) USING BTREE,
  UNIQUE KEY `uni_domain_site_context_path` (`domain`,`site_context_path`) USING BTREE,
  KEY `domain` (`domain`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT='站点表';
