-- 建表语句sql
DROP TABLE IF EXISTS component_cms_content;
CREATE TABLE `component_cms_content` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `cms_site_id` bigint NOT NULL COMMENT '站点id',
  `cms_channel_id` bigint DEFAULT NULL COMMENT '栏目id',
  `cms_content_category_id` bigint DEFAULT NULL COMMENT '内容分类id',
  `title` varchar(100) DEFAULT NULL COMMENT '标题',
  `author` varchar(100) NOT NULL COMMENT '作者',
  `original` varchar(200) DEFAULT NULL COMMENT '来源，原文，如果是原创，写原创即可',
  `profile` varchar(200) DEFAULT NULL COMMENT '简介',
  `audit_status_dict_id` bigint DEFAULT NULL COMMENT '审核状态，字典id',
  `is_public` tinyint(1) NOT NULL COMMENT '是否发布',
  `public_at` datetime DEFAULT NULL COMMENT '发布时间',
  `content_type_dict_id` bigint DEFAULT NULL COMMENT '内容类型，字典id，article=文章，library=文库，gallery=图库',
  `image_url` varchar(300) DEFAULT NULL COMMENT '图片地址，主要用于列表展示',
  `image_description` varchar(300) DEFAULT NULL COMMENT '图片描述，可能主要用于详情展示，如：图片来源于网络',
  `image_url1` varchar(300) DEFAULT NULL COMMENT '图片地址1，主要用于列表展示',
  `image_description1` varchar(300) DEFAULT NULL COMMENT '图片描述1，可能主要用于详情展示，如：图片来源于网络',
  `image_url2` varchar(300) DEFAULT NULL COMMENT '图片地址2，主要用于列表展示',
  `image_description2` varchar(300) DEFAULT NULL COMMENT '图片描述2，可能主要用于详情展示，如：图片来源于网络',
  `template_path` varchar(200) NOT NULL COMMENT '内容模板路径',
  `template_index` varchar(200) NOT NULL COMMENT '内容模板,默认index.html',
  `static_path` varchar(200) DEFAULT NULL COMMENT '内容静态页存放路径',
  `pv` int NOT NULL COMMENT '页面访问量,页面展示次数',
  `iv` int NOT NULL COMMENT '页面访问ip数,一天之内相同IP地址只被计算一次',
  `uv` int NOT NULL COMMENT '页面访问用户数,页面访问电脑客户端数,一天之内相同cookie的访问只被计算1次',
  `seq` int NOT NULL COMMENT '排序,默认按该字段升序排序',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `audit_status_dict_id` (`audit_status_dict_id`) USING BTREE,
  KEY `cms_site_id` (`cms_site_id`) USING BTREE,
  KEY `cms_channel_id` (`cms_channel_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='内容表';
