DROP TABLE IF EXISTS component_user;
CREATE TABLE `component_user` (
  `id` bigint NOT NULL COMMENT '用户ID',
  `name` varchar(50) NULL COMMENT '姓名，真实姓名',
  `nickname` varchar(50) NOT NULL COMMENT '昵称，模糊查询',
  `gender_dict_id` bigint DEFAULT NULL COMMENT '性别，字典id',
  `avatar` varchar(500) DEFAULT NULL COMMENT '头像，建议图片相对路径',
  `serial_no` varchar(50) DEFAULT NULL COMMENT '用户编号，可以做为员工编号',
  `comp_id` bigint DEFAULT NULL COMMENT '公司id，冗余字段，由dept_id对应公司派生',
  `dept_id` bigint DEFAULT NULL COMMENT '部门id',
  `is_virtual` tinyint(1) NOT NULL COMMENT '是否虚拟用户，虚拟用户代表不是一个真正存在的用户',
  `is_lock` tinyint(1) NOT NULL COMMENT '锁定状态，0=未锁定；1=锁定',
  `lock_reason` varchar(255) DEFAULT NULL COMMENT '锁定原因',
  `category_dict_id` bigint DEFAULT NULL COMMENT '用户分类字典，标识是哪一类用户，比如后台用户等',
  `group_flag` varchar(255) DEFAULT NULL COMMENT '分组标识',
  `source_from_dict_id` bigint DEFAULT NULL COMMENT '用户来源，字典id',
  `is_expired` tinyint(1) NOT NULL COMMENT '是否过期，过期后该密码不能登录',
  `expired_reason` varchar(255) DEFAULT NULL COMMENT '过期原因',
  `expire_at` datetime DEFAULT NULL COMMENT '到期时间，为空永不到期',
  `effective_at` datetime NULL DEFAULT NULL COMMENT '生效日期，从什么时候开始生效',
  `effective_at_trigger_dict_id` bigint NULL DEFAULT NULL COMMENT '生效日期，触发方式，一般为首次登录触发',
  `effective_days` int NULL DEFAULT NULL COMMENT '有效天数,0或空为不限制',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `serial_no` (`serial_no`) USING BTREE COMMENT '一个用户只能有一个编码',
  KEY `gender` (`gender_dict_id`) USING BTREE,
  KEY `is_lock` (`is_lock`) USING BTREE,
  KEY `dept_id` (`dept_id`) USING BTREE,
  KEY `nickname` (`nickname`) USING BTREE,
  KEY `comp_id` (`comp_id`) USING BTREE,
  KEY `group_flag` (`group_flag`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户表';
