DROP TABLE IF EXISTS component_lowcode_model_item;
CREATE TABLE `component_lowcode_model_item` (
  `id` bigint NOT NULL COMMENT 'ID',
  `column_name` varchar(100) NOT NULL COMMENT '字段名称',
  `property_name` varchar(100) NOT NULL COMMENT '实体属性名称',
  `jdbc_type` varchar(255) NOT NULL COMMENT '数据库类型',
  `property_type` varchar(255) NOT NULL COMMENT '实体属性类型',
  `property_full_type` varchar(255) DEFAULT NULL COMMENT '实体属性类型全路径',
  `comment_full` varchar(255) NOT NULL COMMENT '字段注释,完整的注释',
  `comment_simple` varchar(255) NOT NULL COMMENT '字段注释,简洁注释，提取列注释的第一个逗号前面的，常用于swagger',
  `default_value` varchar(255) DEFAULT NULL COMMENT '默认值',
  `is_unique` tinyint(1) NOT NULL COMMENT '是否唯一，一般有唯一索引就是唯一，不算主键',
  `is_required` tinyint(1) NOT NULL COMMENT '是否必填',
  `is_key` tinyint(1) NOT NULL COMMENT '是否主键',
  `is_key_identity` tinyint(1) NOT NULL COMMENT '是否主键自增',
  `is_key_word` tinyint(1) NOT NULL COMMENT '是否为关键字',
  `column_length` int DEFAULT NULL COMMENT '字段长度',
  `fraction_length` int DEFAULT NULL COMMENT '字段小数位长度',
  `is_foreign_key` tinyint(1) NOT NULL COMMENT '字段是否外键',
  `lowcode_model_id` bigint NOT NULL COMMENT '模型id',
  `design_json` text DEFAULT NULL COMMENT '设计json数据，包括一般CRUD相关配置信息',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述,注意事项等',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `version` (`version`) USING BTREE,
  KEY `lowcode_model_id` (`lowcode_model_id`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='低代码模型项目表';
