-- 建表语句sql
DROP TABLE IF EXISTS component_data_query_data_api;
CREATE TABLE `component_data_query_data_api` (
  `id` bigint NOT NULL COMMENT 'ID',
  `url` varchar(300) NOT NULL COMMENT '接口地址',
  `name` varchar(100) NOT NULL COMMENT '接口名称',
  `data_query_datasource_api_id` bigint DEFAULT NULL COMMENT '数据查询数据源接口id，接口直连时使用',
  `adapt_type_dict_id` bigint DEFAULT NULL COMMENT '适配类型，字典id，直连、聚合等',
  `adapt_config_json` text COMMENT '接口适配配置json',
  `in_param_type_dict_id` bigint DEFAULT NULL COMMENT '入参类型，字典id，为空表示无入参',
  `in_param_example_config_json` mediumtext COMMENT '入参示例，纯文本展示',
  `in_param_test_case_data_config_json` mediumtext COMMENT '入参测试用例数据，该数据应该配合入参配置json或json配置识别',
  `in_param_doc_config_json` mediumtext COMMENT '入参文档配置json',
  `in_param_validate_config_json` mediumtext COMMENT '入参校验配置json',
  `in_param_ext_config_json` mediumtext COMMENT '入参扩展配置json',
  `out_param_type_dict_id` bigint DEFAULT NULL COMMENT '出参类型，字典id',
  `out_param_example_config_json` mediumtext COMMENT '出参示例，纯文本展示',
  `out_param_doc_config_json` mediumtext COMMENT '出参文档配置json',
  `out_param_success_config_json` mediumtext COMMENT '出参成功或失败配置json',
  `out_param_trans_config_json` mediumtext COMMENT '出参翻译配置json',
  `out_param_ext_config_json` mediumtext COMMENT '出参扩展配置json',
  `response_type_dict_id` bigint DEFAULT NULL COMMENT '输出类型，字典id，用来定义响应数据格式',
  `pageable_adapter_config_json` mediumtext COMMENT '分页适配信息配置json',
  `dict_config_json` text COMMENT '字典配置json，为入参和出参字典提供支持',
  `is_use_remote` tinyint(1) NOT NULL COMMENT '是否使用远程服务',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述,注意事项等',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `url` (`url`),
  KEY `version` (`version`) USING BTREE,
  KEY `name` (`name`) USING BTREE,
  KEY `data_query_datasource_api_id` (`data_query_datasource_api_id`) USING BTREE,
  KEY `response_type_dict_id` (`response_type_dict_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='数据查询数据接口表';
