spring:
  application:
    # 应用名称
    name: particle-demo-start
  profiles:
    include:
      - knife4j
      - swagger
      - log4j2
      - sleuth
      - datasource
      - mybatis-plus
      - mybatis-plus-tenant
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为 master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost/particle_test?${particle.datasource.mysql.url-query}
          username: root
          password: rootroot
          driver-class-name: ${particle.datasource.mysql.driver} # 3.2.0开始支持SPI可省略此配置
  # 注意，这里的配置是spring的但实现已经自定义，参考 global-datasource-boot-starter 组件 sqlinit 包实现
  sql:
    init:
      schema-locations:
        - classpath:db/schema.particle-demo.sql
        - classpath:db/schema.area.sql
        - classpath:db/schema.dict.sql
        - classpath:db/schema.func.sql
        - classpath:db/schema.generator.sql
        - classpath:db/schema.user.sql
        - classpath:db/schema.role.sql
        - classpath:db/schema.global_message_event.sql
        - classpath:db/schema.global_message_event_consume_record.sql
        - classpath:db/schema.low-code.sql
        - classpath:db/schema.data-query.sql
        - classpath:db/schema.tenant.sql
        - classpath:db/schema.dept.sql
        - classpath:db/schema.op-log.sql
        - classpath:db/schema.tracking.sql
      data-locations:
        - classpath:db/data.particle-demo.sql
        - classpath:db/data.area.sql
        - classpath:db/data.dict.sql
        - classpath:db/data.func.sql
        - classpath:db/data.generator.sql
        - classpath:db/data.user.sql
        - classpath:db/data.role.sql
        - classpath:db/data.low-code.sql
        - classpath:db/data.low-code.demo.sql
        - classpath:db/data.tools.sql
        - classpath:db/data.data-query.sql
        - classpath:db/data.data-query.demo.sql
        - classpath:db/data.tenant.sql
        - classpath:db/data.dept.sql
        - classpath:db/data.op-log.sql
        - classpath:db/data.tracking.sql
      mode: ALWAYS # ALWAYS NEVER
  servlet:
    multipart:
      max-request-size: 500MB
      max-file-size: 50MB
server:
  servlet:

    encoding:
      # 在接收请求和返回数据，强制 utf-8 编码
      # encoding 配置默认为 utf-8 编码 参见：org.springframework.boot.web.servlet.server.Encoding.DEFAULT_CHARSET
      force: true

particle:
  project-info:
    component:
      # 后端组件全部启用
      enable:
        all: true
  captcha:
    filter:
      enabled: true
      uris:
        # 登录添加验证码校验
        - /login
  # 该配置对应 com.particle.global.oss.GlobalOssProperties 配置属性
  oss:
    defaultClient: testLocal
    concatEndpoint: false
    local:
      testLocal:
        # 访问的地址
        endpoint: http://localhost:8080/oss/download
        basePath: /Users/yw/temp/localosstest
        bucketName: localtestbucket