<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>component</artifactId>
        <groupId>com.particle</groupId>
        <version>7.0.3-beta-SNAPSHOT</version>
    </parent>
    <modules>
        <module>gateway-webmvc-start</module>
        <module>gateway-webflux-start</module>
    </modules>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>gateway</artifactId>
    <packaging>pom</packaging>
    <properties>
    </properties>

</project>
