-- 建表语句sql
DROP TABLE IF EXISTS component_report_segment_template;
CREATE TABLE `component_report_segment_template` (
  `id` bigint NOT NULL COMMENT '模板ID',
  `code` varchar(200) DEFAULT NULL COMMENT '编码，唯一',
  `name` varchar(100) NOT NULL COMMENT '模板名称，仅做展示',
  `data_resolve_script` varchar(2000) COMMENT '数据获取脚本，目前仅支持groovy脚本',
  `render_condition_script` varchar(2000) COMMENT '渲染条件脚本，目前仅支持groovy脚本',
  `compute_template` varchar(1000) DEFAULT NULL COMMENT '计算模板',
  `name_template` varchar(1000) DEFAULT NULL COMMENT '名称模板',
  `name_output_variable` varchar(255) DEFAULT NULL COMMENT '名称输出变量名',
  `content_template` text COMMENT '内容模板',
  `reference_segment_template_id` bigint DEFAULT NULL COMMENT '引用模板id',
  `output_type_dict_id` bigint NOT NULL COMMENT '输出类型字典id，file=文件，dir=目录，segment=片段',
  `output_variable` varchar(255) DEFAULT NULL COMMENT '内容输出变量名',
  `share_variables` varchar(255) DEFAULT NULL COMMENT '共享变量名，多个以逗号分隔，变量类型为Set<String>',
  `seq` int NOT NULL COMMENT '排序,默认按该字段升序排序',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `level` int NOT NULL COMMENT '层级、深度',
  `parent_id` bigint DEFAULT NULL COMMENT '父级',
  `parent_id1` bigint DEFAULT NULL COMMENT 'LEVEL为1的父id',
  `parent_id2` bigint DEFAULT NULL COMMENT 'LEVEL为2的父id',
  `parent_id3` bigint DEFAULT NULL COMMENT 'LEVEL为3的父id',
  `parent_id4` bigint DEFAULT NULL COMMENT 'LEVEL为4的父id',
  `parent_id5` bigint DEFAULT NULL COMMENT 'LEVEL为5的父id',
  `parent_id6` bigint DEFAULT NULL COMMENT 'LEVEL为6的父id',
  `parent_id7` bigint DEFAULT NULL COMMENT 'LEVEL为7的父id',
  `parent_id8` bigint DEFAULT NULL COMMENT 'LEVEL为8的父id',
  `parent_id9` bigint DEFAULT NULL COMMENT 'LEVEL为9的父id',
  `parent_id10` bigint DEFAULT NULL COMMENT 'LEVEL为10的父id',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `code` (`code`) USING BTREE,
  KEY `name` (`name`) USING BTREE,
  KEY `reference_segment_template_id` (`reference_segment_template_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='报告片段模板表';
