version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: particle-rabbitmq
    restart: always
    networks:
      - particle-rabbitmq-net
    environment:
      - "RABBITMQ_DEFAULT_USER=rabbitmq-user"
      - "RABBITMQ_DEFAULT_PASS=rabbitmq-password"
    volumes:
      - particle-rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"

networks:
  particle-rabbitmq-net:
    driver: bridge

volumes:
  particle-rabbitmq-data:
    driver: local