<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>common</artifactId>
        <groupId>com.particle</groupId>
        <version>7.0.3-beta-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>common-constant</artifactId>

    <description>
        通用常量定义模块，用于集中管理跨模块共享的常量信息，
        仅包含无业务行为的静态常量定义，
        避免在各层中散落硬编码值，不承载业务规则与领域逻辑。
    </description>

    <properties>


    </properties>

    <dependencies>
        <!-- 将全局的经量依赖到common里面来，方便使用 -->
        <dependency>
            <groupId>com.particle</groupId>
            <artifactId>global-common</artifactId>
            <version>${particle.version}</version>
        </dependency>
    </dependencies>

</project>
