-- 建表语句sql
DROP TABLE IF EXISTS component_dream_ssq_code;
CREATE TABLE `component_dream_ssq_code` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `seq_no` int NOT NULL COMMENT '序号，从1开始递增',
  `red_seq_no` int NOT NULL COMMENT '红球序号，从1开始递增',
  `red1` int NOT NULL COMMENT '红球1',
  `red2` int NOT NULL COMMENT '红球2',
  `red3` int NOT NULL COMMENT '红球3',
  `red4` int NOT NULL COMMENT '红球4',
  `red5` int NOT NULL COMMENT '红球5',
  `red6` int NOT NULL COMMENT '红球6',
  `blue` int NOT NULL COMMENT '蓝球',
  `red_sum` int NOT NULL COMMENT '红球和值，红球开奖号码相加之和',
  `red_sum_last` int NOT NULL COMMENT '红球和尾值，开奖号码和值的个位数，范围为0-9。示例：和值15的和尾为5',
  `red_blue_sum` int NOT NULL COMMENT '总和值，红蓝球开奖号码相加之和',
  `red_blue_sum_last` int NOT NULL COMMENT '总和尾值，开奖号码和值的个位数，范围为0-9。示例：和值15的和尾为5',
  `red_span` int NOT NULL COMMENT '红球跨度，红球开奖号码中最大号与最小号的差值',
  `red_ac` int NOT NULL COMMENT '红球ac值，也可称为数字复杂度，是指在一组号码组合中，任意两个数字之间不相同的正差值的总个数再减去“正选号码数量-1”的值',
  `red_region1_ratio` int NOT NULL COMMENT '红1区个数，1-11',
  `red_region2_ratio` int NOT NULL COMMENT '红2区个数，12-22',
  `red_region3_ratio` int NOT NULL COMMENT '红3区个数，23-33',
  `red_odd_ratio` int NOT NULL COMMENT '红奇数个数',
  `red_even_ratio` int NOT NULL COMMENT '红偶数个数',
  `is_has_serial_num` tinyint(1) NOT NULL COMMENT '是否包含连号，即间隔1',
  `serial_times` int NOT NULL COMMENT '红连号个数，如：2 3 22 23 25 33 7则为2，因为2 3算一个，22 23 算一个',
  `max_serial_length` int NOT NULL COMMENT '最大连号长度',
  `is_has_even_serial_num` tinyint(1) NOT NULL COMMENT '是否包含偶连号，即间隔2',
  `even_serial_times` int NOT NULL COMMENT '偶红连号个数，如：2 4 22 24 25 33 7则为2，因为2 4算一个，22 24 算一个',
  `even_max_serial_length` int NOT NULL COMMENT '最大偶红连号长度',
  `is_red_include_blue` tinyint(1) NOT NULL COMMENT '是否红蓝重号，是否红球有和蓝球相等',
  `is_blue_odd` tinyint(1) NOT NULL COMMENT '是否蓝球为奇数，1=奇数，0=偶数',
  `is_opened` tinyint(1) DEFAULT NULL COMMENT '是否已开奖',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `seq_no` (`seq_no`) USING BTREE,
  KEY `red_seq_no` (`red_seq_no`) USING BTREE,
  KEY `red1` (`red1`) USING BTREE,
  KEY `red2` (`red2`) USING BTREE,
  KEY `red3` (`red3`) USING BTREE,
  KEY `red4` (`red4`) USING BTREE,
  KEY `red5` (`red5`) USING BTREE,
  KEY `red6` (`red6`) USING BTREE,
  KEY `blue` (`blue`) USING BTREE,
  KEY `is_opened` (`is_opened`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='双色球号码表';
