-- 建表语句sql
DROP TABLE IF EXISTS component_dream_ssq_code_opened;
CREATE TABLE `component_dream_ssq_code_opened` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `ssq_code_id` bigint NOT NULL COMMENT '双色球号码id',
  `opened_date` date NOT NULL COMMENT '开奖日期',
  `opened_phase_year` int NOT NULL COMMENT '开奖期号年份',
  `opened_phase_num` int NOT NULL COMMENT '开奖期号数',
  `opened_week_day` int NOT NULL COMMENT '开奖星期号，从1-7，7代表星期日',
  `opened_phase` varchar(20) NOT NULL COMMENT '开奖期号',
  `opened_red1` int DEFAULT NULL COMMENT '开奖红球1',
  `opened_red2` int DEFAULT NULL COMMENT '开奖红球2',
  `opened_red3` int DEFAULT NULL COMMENT '开奖红球3',
  `opened_red4` int DEFAULT NULL COMMENT '开奖红球4',
  `opened_red5` int DEFAULT NULL COMMENT '开奖红球5',
  `opened_red6` int DEFAULT NULL COMMENT '开奖红球6',
  `opened_blue` int DEFAULT NULL COMMENT '开奖蓝球',
  `win1_num` int DEFAULT NULL COMMENT '中1等奖注数',
  `win1_amount` int DEFAULT NULL COMMENT '中1等奖单注金额，单位元',
  `win1_total_amount` bigint DEFAULT NULL COMMENT '中1等奖总金额，单位元',
  `win2_num` int DEFAULT NULL COMMENT '中2等奖注数',
  `win2_amount` int DEFAULT NULL COMMENT '中2等奖单注金额，单位元',
  `win2_total_amount` bigint DEFAULT NULL COMMENT '中2等奖总金额，单位元',
  `win3_num` int DEFAULT NULL COMMENT '中3等奖注数',
  `win3_amount` int DEFAULT NULL COMMENT '中3等奖单注金额，单位元',
  `win3_total_amount` bigint DEFAULT NULL COMMENT '中3等奖总金额，单位元',
  `win4_num` int DEFAULT NULL COMMENT '中4等奖注数',
  `win4_amount` int DEFAULT NULL COMMENT '中4等奖单注金额，单位元',
  `win4_total_amount` bigint DEFAULT NULL COMMENT '中4等奖总金额，单位元',
  `win5_num` int DEFAULT NULL COMMENT '中5等奖注数',
  `win5_amount` int DEFAULT NULL COMMENT '中5等奖单注金额，单位元',
  `win5_total_amount` bigint DEFAULT NULL COMMENT '中5等奖总金额，单位元',
  `win6_num` int DEFAULT NULL COMMENT '中6等奖注数',
  `win6_amount` int DEFAULT NULL COMMENT '中6等奖单注金额，单位元',
  `win6_total_amount` bigint DEFAULT NULL COMMENT '中6等奖总金额，单位元',
  `win_total_amount` bigint DEFAULT NULL COMMENT '中奖总金额，单位元',
  `prize_pool_amount` bigint DEFAULT NULL COMMENT '奖池金额，单位元',
  `next_prize_pool_amount` bigint DEFAULT NULL COMMENT '下一期奖池金额，单位元',
  `sale_amount` bigint DEFAULT NULL COMMENT '销售额，单位元',
  `red_cold2_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近2期以内未出现的号码',
  `red_hot2_ratio` int DEFAULT NULL COMMENT '红热号个数，最近2期以内出现过的号码',
  `red_cold3_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近3期以内未出现的号码',
  `red_hot3_ratio` int DEFAULT NULL COMMENT '红热号个数，最近3期以内出现过的号码',
  `red_cold4_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近4期以内未出现的号码',
  `red_hot4_ratio` int DEFAULT NULL COMMENT '红热号个数，最近4期以内出现过的号码',
  `red_cold5_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近5期以内未出现的号码',
  `red_hot5_ratio` int DEFAULT NULL COMMENT '红热号个数，最近5期以内出现过的号码',
  `red_cold6_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近6期以内未出现的号码',
  `red_hot6_ratio` int DEFAULT NULL COMMENT '红热号个数，最近6期以内出现过的号码',
  `red_cold7_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近7期以内未出现的号码',
  `red_hot7_ratio` int DEFAULT NULL COMMENT '红热号个数，最近7期以内出现过的号码',
  `red_cold8_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近8期以内未出现的号码',
  `red_hot8_ratio` int DEFAULT NULL COMMENT '红热号个数，最近8期以内出现过的号码',
  `red_cold9_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近9期以内未出现的号码',
  `red_hot9_ratio` int DEFAULT NULL COMMENT '红热号个数，最近9期以内出现过的号码',
  `red_cold10_ratio` int DEFAULT NULL COMMENT '红冷号个数，最近10期以内未出现的号码',
  `red_hot10_ratio` int DEFAULT NULL COMMENT '红热号个数，最近10期以内出现过的号码',
-- 以下字段冗余自 schema.component_dream_ssq_code.sql 表字段方便查询
  `seq_no` int NOT NULL COMMENT '序号，从1开始递增',
  `red_seq_no` int NOT NULL COMMENT '红球序号，从1开始递增',
  `red1` int NOT NULL COMMENT '红球1',
  `red2` int NOT NULL COMMENT '红球2',
  `red3` int NOT NULL COMMENT '红球3',
  `red4` int NOT NULL COMMENT '红球4',
  `red5` int NOT NULL COMMENT '红球5',
  `red6` int NOT NULL COMMENT '红球6',
  `blue` int NOT NULL COMMENT '蓝球',
  `red_sum` int NOT NULL COMMENT '红球和值，红球开奖号码相加之和',
  `red_sum_last` int NOT NULL COMMENT '红球和尾值，开奖号码和值的个位数，范围为0-9。示例：和值15的和尾为5',
  `red_blue_sum` int NOT NULL COMMENT '总和值，红蓝球开奖号码相加之和',
  `red_blue_sum_last` int NOT NULL COMMENT '总和尾值，开奖号码和值的个位数，范围为0-9。示例：和值15的和尾为5',
  `red_span` int NOT NULL COMMENT '红球跨度，红球开奖号码中最大号与最小号的差值',
  `red_ac` int NOT NULL COMMENT 'ac值，也可称为数字复杂度，是指在一组号码组合中，任意两个数字之间不相同的正差值的总个数再减去“正选号码数量-1”的值',
  `red_region1_ratio` int NOT NULL COMMENT '红1区个数，1-11',
  `red_region2_ratio` int NOT NULL COMMENT '红2区个数，12-22',
  `red_region3_ratio` int NOT NULL COMMENT '红3区个数，23-33',
  `red_odd_ratio` int NOT NULL COMMENT '红奇数个数',
  `red_even_ratio` int NOT NULL COMMENT '红偶数个数',
  `is_has_serial_num` tinyint(1) NOT NULL COMMENT '是否包含连号，即间隔1',
  `serial_times` int NOT NULL COMMENT '连号个数，如：2 3 22 23 25 33 7则为2，因为2 3算一个，22 23 算一个',
  `max_serial_length` int NOT NULL COMMENT '最大连号长度',
  `is_has_even_serial_num` tinyint(1) NOT NULL COMMENT '是否包含偶连号，即间隔2',
  `even_serial_times` int NOT NULL COMMENT '偶连号个数，如：2 4 22 24 25 33 7则为2，因为2 4算一个，22 24 算一个',
  `even_max_serial_length` int NOT NULL COMMENT '最大偶连号长度',
  `is_red_include_blue` tinyint(1) NOT NULL COMMENT '是否红蓝重号，是否红球有和蓝球相等',
  `is_blue_odd` tinyint(1) NOT NULL COMMENT '是否蓝球为奇数，1=奇数，0=偶数',

  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `opened_date` (`opened_date`) USING BTREE,
  KEY `opened_phase_year` (`opened_phase_year`) USING BTREE,
  KEY `opened_phase_num` (`opened_phase_num`) USING BTREE,
  KEY `opened_phase` (`opened_phase`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='双色球开奖表';
