-- 建表语句sql
DROP TABLE IF EXISTS component_openplatform_openapi_record;
CREATE TABLE `component_openplatform_openapi_record` (
  `id` bigint NOT NULL COMMENT '表主键',
  `openplatform_app_id` bigint DEFAULT NULL COMMENT '开放平台应用id',
  `app_id` varchar(255) DEFAULT NULL COMMENT '应用id',
  `user_id` bigint DEFAULT NULL COMMENT '用户id',
  `is_app` tinyint(1) NOT NULL COMMENT '是否为app调用，1=appId调用（app_id字段有值），0=用户页面调用（user_id字段有值）',
  `customer_id` bigint DEFAULT NULL COMMENT '客户id',
  `openplatform_openapi_id` bigint NOT NULL COMMENT '开放接口id，这里只存储接口，不存储分组',
  `request_url` varchar(255) NOT NULL COMMENT '接口地址，空余 openplatform_openapi_id对应的url',
  `request_timestamp` bigint NOT NULL COMMENT '请求时间戳，单位毫秒',
  `request_nonce` varchar(255) NOT NULL COMMENT '请求流水号',
  `request_signature` varchar(255) DEFAULT NULL COMMENT '请求签名,不校验时可以不传，oauth2方式可以不传',
  `request_parameter_md5` varchar(100) DEFAULT NULL COMMENT '请求参数md5',
  `request_handle_at` datetime NOT NULL COMMENT '开始处理时间',
  `response_result_md5` varchar(100) DEFAULT NULL COMMENT '响应结果md5',
  `trace_id` varchar(50) NOT NULL COMMENT '日志追踪id',
  `handle_duration` int NOT NULL COMMENT '处理时长，单位毫秒',
  `is_response_has_effective_value` tinyint(1) NOT NULL COMMENT '是否包含有效响应数据',
  `response_http_status` int NOT NULL COMMENT '响应http状态码',
  `response_business_status` varchar(50) DEFAULT NULL COMMENT '响应业务状态码',
  `is_exist_provider_record` tinyint(1) NOT NULL COMMENT '是否存在供应商调用记录，1=存在，0=不存在',
  `remark` varchar(2000) DEFAULT NULL COMMENT '描述',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `openplatform_app_id` (`openplatform_app_id`),
  KEY `app_id` (`app_id`),
  KEY `user_id` (`user_id`) USING BTREE,
  KEY `customer_id` (`customer_id`),
  KEY `request_url` (`request_url`),
  KEY `request_parameter_md5` (`request_parameter_md5`),
  KEY `response_result_md5` (`response_result_md5`),
  KEY `request_nonce` (`request_nonce`),
  KEY `trace_id` (`trace_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='开放平台开放接口调用记录表';
