DROP TABLE IF EXISTS component_user_login_record;
CREATE TABLE `component_user_login_record` (
  `id` bigint NOT NULL COMMENT '用户ID',
  `user_id` bigint NOT NULL COMMENT '用户id',
  `login_at` datetime NOT NULL COMMENT '登录时间',
  `login_ip` varchar(500) NOT NULL COMMENT '登录ip',
  `device_id` varchar(500) NOT NULL COMMENT '设备id，可以用来唯一标识一个设备',
  `device_name` varchar(255) NOT NULL COMMENT '设备名称，如：xxx的Iphone',
  `user_identifier_id` bigint NOT NULL COMMENT '登录标识id',
  `operating_system` varchar(255) NOT NULL COMMENT '操作系统及版本',
  `session` varchar(500) NOT NULL COMMENT '会话标识，登录成功后的会话',
  `session_md5` varchar(255) NOT NULL COMMENT '会话标识的md5摘要值，考虑到会话标识可能会很长',
  `is_success` tinyint(1) NOT NULL COMMENT '登录是否成功',
  `failed_reason` varchar(255) DEFAULT NULL COMMENT '失败原因',
  `trace_id` varchar(50) NOT NULL COMMENT '追踪id',
  `api_count` bigint NOT NULL COMMENT 'api数量，该次登录请求的api数，登录算第1次',
  `last_active_at` datetime NOT NULL COMMENT '最后活跃时间',
  `logout_at` datetime DEFAULT NULL COMMENT '退出登录时间',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `user_id` (`user_id`),
  KEY `user_id__user_identifier_id` (`user_id`,`user_identifier_id`),
  KEY `session` (`session`),
  KEY `session_md5` (`session_md5`),
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='用户登录记录表';
