-- 建表语句sql
-- import classpath:db/schema.component_op_log.sql
-- import classpath:db/schema.component_op_log_audit_data.sql
-- import classpath:db/error/schema.component_op_log_error.sql
-- import classpath:db/error/schema.component_op_log_error_content.sql