-- 添加一个空注释，否则如果内容为空，报错，或者在配置文件中配置添加前 optional: 缀如： optional:classpath:db/xxxxx.sql
-- import classpath:db/schema.component_navigation_category.sql
-- import classpath:db/schema.component_navigation_site.sql
-- import classpath:db/schema.component_navigation_site_category_rel.sql
-- import classpath:db/schema.component_navigation_static_deploy.sql
-- import classpath:db/schema.component_navigation_friendship_link.sql
-- import classpath:db/schema.component_navigation_submit.sql
-- import classpath:db/schema.component_navigation_site_tag.sql
-- import classpath:db/schema.component_navigation_site_tag_rel.sql
