-- 建表语句sql
-- import classpath:db/app/schema.component_openplatform_app.sql
-- import classpath:db/app/schema.component_openplatform_app_openapi.sql
-- import classpath:db/openapi/schema.component_openplatform_openapi.sql
-- import classpath:db/openapi/schema.component_openplatform_openapi_fee.sql
-- import classpath:db/openapirecord/schema.component_openplatform_openapi_record.sql
-- import classpath:db/openapirecord/schema.component_openplatform_openapi_record_param.sql
-- import classpath:db/provider/schema.component_openplatform_provider.sql
-- import classpath:db/providerrecord/schema.component_openplatform_provider_record.sql
-- import classpath:db/providerrecord/schema.component_openplatform_provider_record_param.sql
