-- 添加一个空注释，否则如果内容为空，报错，或者在配置文件中配置添加前 optional: 缀如： optional:classpath:db/xxxxx.sql
-- 建表语句sql
-- import classpath:db/company/schema.component_crm_company.sql
-- import classpath:db/company/schema.component_crm_dept.sql
-- import classpath:db/customer/schema.component_crm_customer.sql
-- import classpath:db/customer/schema.component_crm_customer_contact.sql
-- import classpath:db/relation/schema.component_crm_customer_relation.sql
-- import classpath:db/relation/schema.component_crm_customer_relation_define.sql
-- import classpath:db/tag/schema.component_crm_customer_tag.sql
-- import classpath:db/tag/schema.component_crm_customer_tag_rel.sql