-- 添加一个空注释，否则如果内容为空，报错，或者在配置文件中配置添加前 optional: 缀如： optional:classpath:db/xxxxx.sql
-- 建表语句sql
-- import classpath:db/schema.component_usage_count_define.sql
-- import classpath:db/schema.component_usage_count_config.sql
-- import classpath:db/schema.component_usage_count_record.sql
-- import classpath:db/schema.component_usage_count_record_detail.sql