-- 建表语句sql
DROP TABLE IF EXISTS component_agi_agent;
CREATE TABLE `component_agi_agent` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `name` varchar(150) NOT NULL COMMENT '智能体名称',
  `avatar` varchar(300) DEFAULT NULL COMMENT '智能体头像',
  `profile` varchar(2000) NOT NULL COMMENT '智能体简介',
  `role` text COMMENT '角色设定，描述人设与回复逻辑的文本',
  `is_use_prologue` tinyint(1) NOT NULL COMMENT '是否使用开场白',
  `prologue` varchar(2000) DEFAULT NULL COMMENT '开场白开场文案',
  `prologue_questions_json` varchar(2000) DEFAULT NULL COMMENT '开场白问题,这应该是一个包含问题的数组，一般填写2-3个',
  `is_auto_prologue` tinyint(1) NOT NULL COMMENT '是否自动生成开场白开场文案，这一般基于历史对话使用ai生成',
  `is_use_auto_ask` tinyint(1) NOT NULL COMMENT '是否使用自动追问，在对话后自动追问问题',
  `preset_dialogue_json` varchar(2000) DEFAULT NULL COMMENT '预设对话，这应该是一个包含预设对话的数组，一般包含system、user、assistant角色的对话',
  `auto_ask_rule` varchar(2000) DEFAULT NULL COMMENT '自动追问规则，描述追问的规则文本',
  `quick_instructions_json` varchar(2000) DEFAULT NULL COMMENT '快捷指令,预设的快速输入，内容是一个数组，数组项包含指令内容、图标等',
  `is_use_online_search` tinyint(1) NOT NULL COMMENT '是否使用联网搜索',
  `is_use_knowledge_base` tinyint(1) NOT NULL COMMENT '是否使用知识库',
  `agi_knowledge_base_id` bigint DEFAULT NULL COMMENT '知识库id',
  `is_use_mcp` tinyint(1) NOT NULL COMMENT '是否使用mcp',
  `mcp_plugins_json` varchar(2000) DEFAULT NULL COMMENT 'mcp插件配置，预留暂没想好',
  `is_use_long_term_memory` tinyint(1) NOT NULL COMMENT '是否使用长期记忆',
  `is_use_voice` tinyint(1) NOT NULL COMMENT '是否使用声音',
  `voice_json` varchar(2000) DEFAULT NULL COMMENT '声音配置，应该为一个对象，配置声音的音色等',
  `model_json` varchar(2000) DEFAULT NULL COMMENT '模型配置，应该为一个对象，配置使用的模型、随机性 (temperature)、核采样 (top_p)、单次回复限制 (max_tokens)、话题新鲜度 (presence_penalty)、频率惩罚度 (frequency_penalty)等',
  `history_message_max_length` int NOT NULL COMMENT '附带历史消息数,一般从0-100',
  `history_message_compression_threshold` int NOT NULL COMMENT '历史消息长度压缩阈值，当未压缩的历史消息超过该值时，将进行压缩',
  `remark` varchar(255) DEFAULT NULL COMMENT '描述',
  `version` int NOT NULL COMMENT '乐观锁字段',
  `tenant_id` bigint DEFAULT NULL COMMENT '租户id',
  `create_at` datetime NOT NULL COMMENT '创建时间的时间戳',
  `create_by` bigint DEFAULT NULL COMMENT '创建人',
  `update_at` datetime DEFAULT NULL COMMENT '修改时间的时间戳',
  `update_by` bigint DEFAULT NULL COMMENT '修改人',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `name` (`name`) USING BTREE,
  KEY `version` (`version`) USING BTREE,
  KEY `create_at` (`create_at`) USING BTREE,
  KEY `update_at` (`update_at`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin COMMENT='智能体表';
