<!DOCTYPE html>
<html lang="zh-CN">
<head>
    [#include "include/global_meta.ftlh"/]

    <meta name="description" content="">
    <meta name="author" content="">

    <title>${site.name}</title>

    [#include "include/global_favicon.ftlh"/]

    <!-- Custom styles for this template -->
    <style>

    </style>

    [#include "include/global_css.ftlh"/]
    [#include "include/global_js_in_head.ftlh"/]

</head>
<body>
[#include "include/global_navigation.ftlh"/]

<div class="main-wrapper  container">
    <h1>你好，世界！首页模板</h1>
</div>

[#include "include/global_footer.ftlh"/]

[#include "include/global_js_in_foot.ftlh"/]

<!-- Custom javascript for this template -->
<script>

</script>
</body>
</html>
